docker:
  registry: registry.cn-shanghai.aliyuncs.com
  registry_prefix: docker.test.com/jaja
  default_push: false
  expose_port: 8080
  username: test
  password: test
server:
  host: 0.0.0.0
  port: 8000
  username: admin
  password: admin
  default_image_format: '{registry}/{jar_basename}'
  default_template: dragonwell8.Dockerfile
templates:
  enabled: true
  directory: dockerfiles
  default: simple
