docker:
  registry: docker.trt.com
  registry_prefix: docker.demo.com/demo
  default_push: false
  expose_port: 8080
server:
  host: 0.0.0.0
  port: 8000
  username: admin
  password: admin
  default_image_format: '{registry}/{jar_basename}'
  default_template: dragonwell8.Dockerfile
templates:
  enabled: true
  directory: dockerfiles
  default: simple
